/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ktcodeshift.example

import ktcodeshift.FileInfo
import ktcodeshift.applyTransform
import kotlin.test.Test
import kotlin.test.assertEquals

class FlattenListTransformTest {
    @Test
    fun transform() {
        val changedSource = applyTransform(FlattenListTransform(), object : FileInfo {
            override val path = "Test.kt"
            override val source = """
                package testing
                
                val a = listOf(listOf(1, 2), listOf(3))
            """.trimIndent()
        })

        assertEquals("""
            package testing
            
            val a = listOf(1, 2, 3)
        """.trimIndent().trim(), changedSource.trim())
    }
}
