name: Java CI

on: [ push ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build

      - name: Create release on tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ktcodeshift-cli/build/distributions/*

      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

      - name: Update formula on tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: "mislav/bump-homebrew-formula-action@v2"
        with:
          download-url: https://github.com/orangain/ktcodeshift/releases/download/${{ steps.extract-version.outputs.tag-name }}/ktcodeshift-${{ steps.extract-version.outputs.tag-name }}.tar.gz
          formula-name: ktcodeshift
          homebrew-tap: orangain/homebrew-tap
          create-pullrequest: true
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
