name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: app/build/distributions/
          if-no-files-found: error

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: distributions
      - name: Rename artifacts
        run: |
          echo Before:
          ls
          mv ktcodeshift.tar ktcodeshift-${GITHUB_REF##*/}.tar
          mv ktcodeshift.zip ktcodeshift-${GITHUB_REF##*/}.zip
          echo After:
          ls

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.tar
            *.zip

